-- Daily + Weekly templates
local daily_template = [[
# %A, %B %d, %Y

Weather: 🌡️🌞 ☁️ ☔ ❄️ ⚡ | Indoor RH (AM/PM): ... / ...

## Morning Protocol (empty stomach)
- [ ] 200–300 ml warm water + pinch sea salt (~⅛ tsp) @ ...:...
- Notes (taste, nausea, reflux): .....................

## Health — Core Tracking (Phase 1)

### Bowel Movement (BM) Log
- BM today (Y/N): ...
- Time(s): ...:... / ...:...
- Bristol type (1–7): ...
- Ease (1=hard/strain, 5=effortless): ...
- Visible mucus/blood (Y/N): ... | Urgency (0–3): ...
- Notes: .....................

### Symptoms (0=none, 3=severe)
- Bloating ... | Cramps ... | Nausea ... | Reflux ... | Headache ...
- Sinus/Throat irritation ... | Itch/Histamine ... | Fatigue ... | Brain fog ...
- Sleepiness after meals ... | Dizziness with exertion ...

### Sleep (last night)
- Bed: ...:... | Wake: ...:... | Awakenings #: ...
- Dream intensity (0–3): ... | Sleep paralysis (Y/N): ...
- Rested on waking (0–3): ...

### Protocol Timing & Doses
- Flaxseed 1 Tbsp (~10 g) with breakfast @ ...:... (Taken Y/N): ...
- Psyllium (whole husk) ½–1 tsp in water @ 10:30 (≥90 min from food/supps) ➜ Extra water glass (Y/N): ...
- Magnesium citrate 200–300 mg after dinner @ ...:... (Dose: ... mg)
- Extras today (tick): [ ] Ginger tea  [ ] Thyme tea  [ ] Chamomile  [ ] Rooibos
- Hydration total (L): ...

## Food Log (brief)
### Breakfast (07:00–08:00)
- Menu: .....................
- Rice cakes: ... (1–2) | Veg topping: .....................
- Add-ons: [ ] Avocado  [ ] Tahini  [ ] Seeds  [ ] Olive oil  [ ] Lemon

### Lunch (12:00–13:00)
- Menu: .....................

### Dinner (18:00–19:00)
- Menu: .....................

### Snacks (time + item)
- ...:... .....................
- ...:... .....................

## Training / Activity
- Type: [ ] Walk  [ ] Strength  [ ] Bike/Row  [ ] Mobility
- Duration: ... min | Effort (RPE 1–10): ...
- Any dizziness/near-faint? (Y/N): ... | Notes: .....................

## Triggers / Exposures (today)
- Damp/smell? (Y/N): ... | Visible dust specks? (Y/N): ...
- New/old items brought in: .....................
- Other: .....................

# Notes
- .....................
- .....................

## Work

## Personal
]]

local weekly_template = [[
# Week %W %B %Y — Summary

## Totals / Averages
- BMs: ... / 7 days  |  Avg Bristol: ...  |  Avg Ease: ...
- Avg awakenings/night: ...  |  Dream intensity avg: ...  |  Paralysis episodes: ...
- Training sessions: ... (total minutes: ...)  |  Dizziness episodes: ...
- Hydration avg (L/day): ...  |  Magnesium avg (mg): ...

## Protocol Adherence (check counts)
- Salt water AM: .../7   |  Flax with breakfast: .../7   |  Psyllium 10:30: .../7   |  Magnesium after dinner: .../7
- Tea rotation: Chamomile ... / Thyme ... / Ginger ... / Rooibos ...

## Symptoms trend (0–3; ↓ better, ↑ worse)
- Bloating: ... → ...  |  Cramps: ... → ...  |  Nausea: ... → ...
- Sinus/Throat: ... → ...  |  Fatigue: ... → ...
- Brain fog: ... → ...  |  Dizziness with exertion: ... → ...

## Triggers/Environment
- Avg indoor RH% (AM/PM): ... / ...   |  Notable exposures: .....................

## Notes & Next Tweaks
- What worked: .....................
- What didn’t: .....................
- Planned adjustments for next week: .....................
]]

return {
	"jakobkhansen/journal.nvim",
	config = function()
		require("journal").setup({
			filetype = "md",
			root = "~/journal",
			date_format = "%d/%m/%Y",
			autocomplete_date_modifier = "end",
			journal = {
				format = "%Y/%m-%B/daily/%d-%A",
				template = daily_template,
				frequency = { day = 1 },
				entries = {
					day = {
						format = "%Y/%m-%B/daily/%d-%A",
						template = daily_template,
						frequency = { day = 1 },
					},
					week = {
						format = "%Y/%m-%B/weekly/week-%W",
						template = weekly_template,
						frequency = { day = 7 },
						date_modifier = "monday",
					},
					month = {
						format = "%Y/%m-%B/%B",
						template = "# %B %Y\n",
						frequency = { month = 1 },
					},
					year = {
						format = "%Y/%Y",
						template = "# %Y\n",
						frequency = { year = 1 },
					},
				},
			},
		})
	end,
}
